apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    name: netology-web
spec:
  containers:
  - name: netology-web
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
      - containerPort: 8080
        name: netology-port

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    name: netology-web
  ports:
  - name: svc-netology-port
    protocol: TCP
    port: 8080
    targetPort: netology-port