apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts: 
          - name: pv-local
            mountPath: /tmp/pv-local

      - name: busybox
        image: busybox
        volumeMounts:
          - name: pv-local
            mountPath: /tmp/pv-local
        command: ['sh', '-c', 'while true; do date +%X >> /tmp/pv-local/output.txt; sleep 5; done']
      
      volumes:
        - name: pv-local
          persistentVolumeClaim:
            claimName: pvc01

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mypv"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi