apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:          
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: nginx-port
      
      - name: multitool
        image: wbitt/network-multitool  
        env:
        - name: HTTP_PORT
          value: "8080"   
        ports:
        - containerPort: 8080
          name: multi-port

---

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: nginx
      port: 9001
      protocol: TCP
      targetPort: 80

    - name: multi
      port: 9002
      protocol: TCP
      targetPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - image: wbitt/network-multitool
    name: multitool


---

apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      nodePort: 30080
